### ISSUE TITLE
Seek and Destroy (incoherent name calling)

### ISSUE THREAD

**Issue by eupedrosa** [lardemua/AtlasCarCalibration#100]
An example of this issues was reported in #99 by @miguelriemoliveira

**Comment by miguelriemoliveira** [comment]
My suggestion: We get toghether for an afternoon in early January and refactor everything we think is needed ... what do you think?

**Comment by eupedrosa** [comment]
:+1: I agree. We should dedicate some time just to solve this *small* things.
Early January is fine.

**Comment by miguelriemoliveira** [comment]
#47 #55 and #60 should also be included in this sweep ...

**Comment by miguelriemoliveira** [comment]
**collect_and_label** should be **label_and_collect**, that's the correct sequence ...

**Comment by miguelriemoliveira** [comment]
Revise the structure of the json collections file

**Comment by miguelriemoliveira** [comment]
#156 is handling this. Closing.
