### ISSUE TITLE
Compare eye-in-hand (and similars) with VISP using reprojection error

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/AtlasCarCalibration#101]
Hi @eupedrosa ,

yesterday while discussing you told me to create an issue, don't remember what it was about. do you remember? For now this is a meta-issue to create the issue : - )

**Comment by eupedrosa** [comment]
I think it was about the average re-projection error. But I am not sure.

**Comment by miguelriemoliveira** [comment]
Yes, that was it. Use reprojection error plot to measure how well the eye-in-hand and eye-to-base and both behave vs visp.

**Comment by miguelriemoliveira** [comment]
Glad you remembered ... now you have more work : - )

**Comment by miguelriemoliveira** [comment]
Hi @eupedrosa , it does not make sense to keep this one alive after having success in #114
