### ISSUE TITLE
Displaying camera during the optimization

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/AtlasCarCalibration#105]
It is now possible to view a camera inside rviz during the optimization. This is helpful for monitoring and analyzing the optimization. Some example images:

![image](https://user-images.githubusercontent.com/11350998/71488036-5cd3d700-2816-11ea-93df-580379ddae32.png)

![image](https://user-images.githubusercontent.com/11350998/71488060-71b06a80-2816-11ea-83e5-795e2236f3b5.png)

Had to republish the camera_info_msg during optimization for this ...

**Comment by eupedrosa** [comment]
Looks nice :+1:
