### ISSUE TITLE
Why is our Camera Projection Matrix different from the camera Matrix

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/AtlasCarCalibration#108]
Following #106 we found out that in our intrinsic camera calibrations the camera_info_msgs have different **P** and **K** matrices.

for monocular cameras they should be the same:

https://answers.ros.org/question/223318/camera_calibration-projection-matrix-and-camera-matrix-not-the-same/

This is a question from 2015 with no answers ...

**Comment by miguelriemoliveira** [comment]
@eupedrosa and @afonsocastro , do you know anything about this?

**Comment by eupedrosa** [comment]
The **P** and **K** have the same values in my dataset. The cameras are a Kinect and an Orbbec Astra.

**Comment by miguelriemoliveira** [comment]
Well, now this is even more confusing. If you read through #65 can you spot anything you did different?

@afonsocastro how did you do your intrinsic calibration? https://wiki.ros.org/camera_calibration ?

And this scale slider was on which number?

![image](https://user-images.githubusercontent.com/11350998/71545420-b6591480-2982-11ea-8cd1-34173088ea17.png)

**Comment by miguelriemoliveira** [comment]
I thinks this was occurring only for an atlascar2 bagfile. Closing for now.
