### ISSUE TITLE
Lidar objective function - simple optimization tests

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/AtlasCarCalibration#109]
Try to figure out if the current cost function for 2D lasers is working and sufficient.

Right now we have the following residuals:

- extrema points
- beam (orthogonal)
- inner points

Simplest test: only right laser as sensor, anchored sensor right laser, only one collection.

![image](https://user-images.githubusercontent.com/11350998/71527297-b00b5f80-28d2-11ea-89dc-8ea09173aa1b.png)

There seems to be some problem since the chessboard should move up to get less score from the inner points ... will investigate.

**Comment by miguelriemoliveira** [comment]
Hi @afonsocastro,

I need your help. The laser orthogonal distance is returning negative values (see figure bellow). I know you and @eupedrosa had a big discussion on whether we could or could not have the errors in absolute. What was the result of that discussion? Residuals can be absolute, right?

![Uploading image.png…]()

**Comment by miguelriemoliveira** [comment]
Redesigned the inner points distance (there are some things about Afonso's implementation I did not understand.

Tried several stuff to get better results:

 - Using only the vertical inner points
 - Using absolute beam distance
 - Using several collections
 - Discarding leftmost and rightmost detected inner points, which are often outliers

Still cannot converge to a satisfactory result. I believe this funcion has local minima because of the image bellow:

![image](https://user-images.githubusercontent.com/11350998/71541245-cf939e00-294d-11ea-9256-74ea8d032fdd.png)

**Comment by miguelriemoliveira** [comment]
For collection 3 converges to this ... strange 

![image](https://user-images.githubusercontent.com/11350998/71543838-93713500-296f-11ea-848e-cce57ea5c971.png)

**Comment by eupedrosa** [comment]
So many things to discuss. @miguelriemoliveira, what a *productive* Christmas. 

The residuals can be negative as long as the derivative is in agreement. We are using numerical differentiation so, no problem there. 

If I am not mistaken, the laser labels are not validated, right? We could fit a line to make sure it is a line. Then, we could use that line to interpolate points or even extrapolate the edge points. In a way, the optimization already tries to fit the points to a line in the chess plane.

**Comment by miguelriemoliveira** [comment]
Hi @eupedrosa , thanks, but the holiday season is not over yet : -).

> The residuals can be negative as long as the derivative is in agreement. We are using numerical differentiation so, no problem there.
For me it would be much easier to use the absolute value ... is that ok?

> If I am not mistaken, the laser labels are not validated, right? We could fit a line to make sure it is a line. Then, we could use that line to interpolate points or even extrapolate the edge points. In a way, the optimization already tries to fit the points to a line in the chess plane.
That's a good idea, and perhaps an alternative to #110. Can you please create an issue for that?

**Comment by eupedrosa** [comment]
> For me it would be much easier to use the absolute value ... is that ok?

Yes, it is ok.

> That's a good idea, and perhaps an alternative to #110. Can you please create an issue for that?

I will open the issue.

**Comment by miguelriemoliveira** [comment]
Thanks.

**Comment by miguelriemoliveira** [comment]
Still the same problem. 

![image](https://user-images.githubusercontent.com/11350998/71551010-99e5c800-29d4-11ea-9a89-a0c193304c66.png)

Reduced the complexity of the problem:

  - Only using residual extrema left (not extrema right)
  - Not using inner residuals
  - Tried without beam residuals (same result)

The solution never converges to the left limit of the chessboard ... bug bug ...

Tomorrow I will study this, even if I have to draw lines to the selected points in the limits.

**Comment by miguelriemoliveira** [comment]
Found the problem ... the limit points also contain the point 0,0.
In this image the magenta capsules are all the limit points. 0,0 is also there!

![image](https://user-images.githubusercontent.com/11350998/71554465-64160300-2a17-11ea-9310-bcc7d9861a11.png)

This cause the optimization to converge to positioning the left extrema at 0,0

**Comment by miguelriemoliveira** [comment]
Without the limit point at 0,0 now it converges as it should ...

![image](https://user-images.githubusercontent.com/11350998/71555163-bc053780-2a20-11ea-8bfc-adee7b183580.png)

**Comment by miguelriemoliveira** [comment]
@afonsocastro this was a nasty bug! You owe me a coffee!

**Comment by miguelriemoliveira** [comment]
OK, so now I am working on getting the optimization to converge with multiple collections. Using the lidar only it seems to work perfectly, e.g. for 3 collections:

![image](https://user-images.githubusercontent.com/11350998/71589232-0c14f480-2b1c-11ea-94d0-cbe580e04d96.png)

![image](https://user-images.githubusercontent.com/11350998/71589240-1636f300-2b1c-11ea-9639-342be3dfc1b3.png)

Average cost of laser is 10 times more...

```
Avg residuals per msg_type:
 {'Image': nan, 'LaserScan': 0.0064529082363795169}
```

However, if I add the top_left_camera to the optimization and anchor it, the optimization does not work the same way. The optimization converges to this:

![image](https://user-images.githubusercontent.com/11350998/71589390-96f5ef00-2b1c-11ea-9cf5-a62897e62e34.png)

![image](https://user-images.githubusercontent.com/11350998/71589400-a1b08400-2b1c-11ea-8312-5c68ca554d27.png)

and the avg error is 

Avg residuals per msg_type:
 {'Image': 0.38787829849551864, 'LaserScan': 0.091845670421972253}

**Comment by miguelriemoliveira** [comment]
So what does it mean? Adding the camera made the optimization loose a degree of freedom. Since the camera is anchored, the pose of the chessboards is also fixed, or the residual related with the camera will rise.

But 9 centimeters error is too much, there should a better solution ... I am confused ...

**Comment by miguelriemoliveira** [comment]
Using hte intrinsics does not help at all ... 

![image](https://user-images.githubusercontent.com/11350998/71590011-e6d5b580-2b1e-11ea-87f8-b90e79bb1f88.png)


What is strange about these results is that from the image above and the dark blue collection, it seems that the laser must move back (negative xx) to make the measurements better fit the chessboard, but this image:

![image](https://user-images.githubusercontent.com/11350998/71590068-1be20800-2b1f-11ea-9433-874db7fb8f99.png)

shows that the other two collections (brown and cyan) need the laser to move forward (x positive) to put the measurements of the chessboard. 

So I would say the algorithm is doing what is expected, and converges to a middles ground in an attempt to reduce the all the residuals ... but what does this mean?

**Comment by eupedrosa** [comment]
Did you try the optimization without optimizing the intrinsic?

**Comment by miguelriemoliveira** [comment]
Here is the dataset I am using. 

[dataset_23_dez_2019.tar.gz](https://github.com/lardemua/AtlasCarCalibration/files/4010409/dataset_23_dez_2019.tar.gz)

**Comment by miguelriemoliveira** [comment]
Using orthogonal error instead of beam resulted in the same problem ...

**Comment by miguelriemoliveira** [comment]
Dividing all image residuals by 100, e.g. this code on 212 of objective_function.py

`local_residuals = [x/100 for x in local_residuals]`

gets good results:

![Screenshot at 2019-12-30 17-37-31](https://user-images.githubusercontent.com/11350998/71593392-bea08380-2b2b-11ea-9144-6bda24fcccf2.png)

![Screenshot at 2019-12-30 17-30-02](https://user-images.githubusercontent.com/11350998/71593401-c6602800-2b2b-11ea-8f77-f8a4e40b285d.png)

Residuals are 3 pixels (must multiply back by 100) and 0.6 cm average

```
Avg residuals per msg_type:
 {'Image': 0.029769675054920747, 'LaserScan': 0.0067155425162651059}
```

#104 made it work ... will try with many collections ...

**Comment by miguelriemoliveira** [comment]
I think it also worked using many collections 

![image](https://user-images.githubusercontent.com/11350998/71593652-ce6c9780-2b2c-11ea-8c96-827d9516a89f.png)

And what's better, the height of the laser scans seems reasonable. We are not using inner points residuals here ...

**Comment by miguelriemoliveira** [comment]
So I guess we should explore #104 . Next I should try with a reasonable first guess (including of the anchored sensor) to see if the pose of the laser w.r.t the car chassis makes any sense.

**Comment by miguelriemoliveira** [comment]
Using inner residuals the av errors are similar, the result places the laser beam much higher in the chessboard, which seems more realistic ... 

![image](https://user-images.githubusercontent.com/11350998/71594182-d3324b00-2b2e-11ea-92d1-8548e51a4792.png)

I am not sure this test about using the inner points is conclusive ...

**Comment by miguelriemoliveira** [comment]
Closing this issue. Conclusions taken from all these tests:

  - inner points, beam, orthogonal (not used), and extrema all seem to be working as intended (refactored some code by @afonsocastro )
  - Chessboard poses inferred by the cameras are not consistent with those from the lidars (top_left_camera and right_laser tests). This inconsistency makes it so that either the residuals of the cameras or the one of the lidars increases. We must balance this compromise, probably using weights (#104).
 - Still not clear why this inconsistency occurs, camera's intrinsics or problem with dataset .
