### ISSUE TITLE
Reset marker poses

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/AtlasCarCalibration#11]
Hi @afonsocastro,

we should have an additional option in the rviz menu to reset all marker poses to the original position. Can you implement?

**Comment by afonsocastro** [comment]
Hi @miguelriemoliveira,
yes, it's better. I'll implement

**Comment by miguelriemoliveira** [comment]
So you still did not go to bed????? :-)

**Comment by miguelriemoliveira** [comment]
Is it working?

A Qua, 15/05/2019, 13:02, afonsocastro <notifications@github.com> escreveu:

**Comment by miguelriemoliveira** [comment]
:)

**Comment by miguelriemoliveira** [comment]
Confirmed. Congrats.

It is working. BTW, did you have to reposition also the markers?

**Comment by afonsocastro** [comment]
The resetToInitialPose function put de markers in the initial pose too, not only the sensors
