### ISSUE TITLE
Time drift fails detection when only one sensor is used

### ISSUE THREAD

**Issue by eupedrosa** [lardemua/AtlasCarCalibration#113]
@miguelriemoliveira, the data collector fails when only one sensor is available.

https://github.com/lardemua/AtlasCarCalibration/blob/e59f5a0da14c47a3a03bd368fc96a11dff18aae1/interactive_calibration/src/interactive_calibration/data_collector_and_labeler.py#L163

`max_delta` return `None`

**Comment by miguelriemoliveira** [comment]
I am on it...

**Comment by miguelriemoliveira** [comment]
Hi @eupedrosa ,

I think I solved it. Can you test and close the issue if its working?

**Comment by eupedrosa** [comment]
Yes, it works. :+1:
