### ISSUE TITLE
Hand-eye static visualization

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/AtlasCarCalibration#115]
The idea is to show all robot poses at the same time ... using serveral robot descriptions of a custom rviz marker with a mesh ...

**Comment by miguelriemoliveira** [comment]
@eupedrosa is doing the dynamic motion visualization by publishing the joint values to make the robot move ... #116.

**Comment by miguelriemoliveira** [comment]
Will start working on this ...

**Comment by miguelriemoliveira** [comment]
Hi @eupedrosa , can you tell me what stuff needs to be installed to use the ur10e?

I will need the urdf and the 3d models for this issue ...

**Comment by eupedrosa** [comment]
I updated the repo with configuration files for the ur10e. For the ur10e main description file you must checkout https://github.com/iris-ua/iris_ur10e.git

**Comment by miguelriemoliveira** [comment]
Thanks. I will look into it.

**Comment by miguelriemoliveira** [comment]
Moving forward. Am able to draw the robot at each collection ...

![image](https://user-images.githubusercontent.com/11350998/73110558-b9eaa780-3efe-11ea-8d55-3321b50b5520.png)

![image](https://user-images.githubusercontent.com/11350998/73110605-fcac7f80-3efe-11ea-93db-57e9d6e81283.png)

![image](https://user-images.githubusercontent.com/11350998/73110629-0df58c00-3eff-11ea-9ab2-beafb5beb1df.png)


Still have a lot of bugs, wil try to clean up tomorrow.

**Comment by eupedrosa** [comment]
Looks nice. We can use this visualization to depict the hand-eye problem.

**Comment by miguelriemoliveira** [comment]
Ok, I think all issues are solved. Will arrange  the code better once I have a chance but for now it is functional.

A nice bonus, we can also produce images with colors associated with each collection, so that we can refer to the figures you've shown in #103. Check it out.

![image](https://user-images.githubusercontent.com/11350998/73124580-eb15b700-3f94-11ea-84e6-8b178988fcc1.png)

![image](https://user-images.githubusercontent.com/11350998/73124646-8d359f00-3f95-11ea-9cb6-84f41c7ddddd.png)

![image](https://user-images.githubusercontent.com/11350998/73124656-9c1c5180-3f95-11ea-9e65-4de4fc96a3a0.png)


Without alfa

![image](https://user-images.githubusercontent.com/11350998/73124673-cff77700-3f95-11ea-9e63-b77de51d2a59.png)

**Comment by eupedrosa** [comment]
:+1:

**Comment by miguelriemoliveira** [comment]
Hi @eupedrosa ,

I am done with adding visualization and a refactoring suggestion to the hand in eye code. 
I changed a lot of stuff but most of them are just suggestions.
We could meet some time next week and talk about them and, if you want, we can roll back.

Also, that talk could decide about  #55 and #100 .

Hand in eye code can visualize the robot in all collections, as well as see the images for each camera.

Can you test it? You will need an additional repository (don't forget to install)

https://github.com/miguelriemoliveira/rospy_urdf_to_rviz_converter

Here's a video of what we can see:

https://youtu.be/NTdRuf9tFjo

**Comment by eupedrosa** [comment]
This look very nice. 
However, something in the camera poses that do not seem right to me. Although, the end pose looks what I was expecting. I will do some tests to make sure everything is OK..

Nonetheless great visualization :+1:
We will definitely use this....

**Comment by eupedrosa** [comment]
@miguelriemoliveira, what is the procedure to view the ros visualization?

**Comment by miguelriemoliveira** [comment]
Hi @eupedrosa ,

thanks. To run the code with visualization I first launch rviz (which launches the roscore as well)

`roslaunch` interactive_calibration eye_calibration_view_optimization.launch rviz:=true

Then, from OptimizationUtils we run:

`clear && test/hand_in_eye/eye_to_base_calib_miguel.py -json ~/datasets/eye_in_hand10/data_collected.json -csf "lambda x: int(x) <50" -rv -si`

Note the new flags -rv (--ros_visualization) which is required to publish ros stuff. If you also want to see the generic matplotlib optimization graphs with add -vo (--view_optimization).

The -si flag (--show_images) makes the code publish the annotated images which can be seen in rviz.

**Comment by eupedrosa** [comment]
It works :+1: 

You can now find a model of the pattern at https://github.com/lardemua/AtlasCarCalibration/tree/master/interactive_calibration/meshes

**Comment by miguelriemoliveira** [comment]
Here we have a charuco pattern ...

![image](https://user-images.githubusercontent.com/11350998/73601284-88a15580-4556-11ea-971a-4fe5d06debde.png)

**Comment by miguelriemoliveira** [comment]
This is complete. Closing.

**Comment by eupedrosa** [comment]
More data
[eye_to_base_2.zip](https://github.com/lardemua/AtlasCarCalibration/files/4159367/eye_to_base_2.zip)
