### ISSUE TITLE
We were wrong!!!

### ISSUE THREAD

**Issue by eupedrosa** [lardemua/AtlasCarCalibration#118]
We were wrong!!!

Optimizing the intrinsic works and works well. Here are some results:
![both_eyes](https://user-images.githubusercontent.com/6196901/72802359-84fefc00-3c43-11ea-8e14-d06e25acd64e.png)

With enough collections we may not need an a priori intrinsic calibration.

**Comment by miguelriemoliveira** [comment]
? did you loose it for good? :-)

**Comment by eupedrosa** [comment]
Check it now...

**Comment by miguelriemoliveira** [comment]
RMSE is is pixels? What do you mean by combined? Summed?

**Comment by eupedrosa** [comment]
RMSE = Root Mean Squared Error (in pixels).
Combined means without separation, as if all errors belonged to an unique sensor.

**Comment by miguelriemoliveira** [comment]
Hum ... and the code for optimizing the intrinsics was not changed? 

We should talk in person, but if I get this straight, the title should be "We were wrong!!! **But that's a very good thing.THE FU#*º"NG INTRINSICS ARE OPTIMIZED AS WELL!**"

Am I right? Man, you really need to start working on your positivity:

https://wheniwork.com/blog/18-simple-ways-to-keep-a-positive-attitude-at-work/

:-)

**Comment by eupedrosa** [comment]
The title is click bait :wink:

> "We were wrong!!! But that's a very good thing.THE FU#*º"NG INTRINSICS ARE OPTIMIZED AS WELL!"

This also my reaction..

By the way, I did intrinsic calibration of both cameras using the camera calibrator from ROS and Matlab -- the Matlab calibrator is very nice. The results are similar to the ones obtained with our optimization process.

**Comment by miguelriemoliveira** [comment]
Well, if that was your reaction then you also are in need of this

https://www.wellandgood.com/good-advice/how-to-stop-swearing/

Every sentence I read sounds off like "this must be in the paper". We should have a subsection of results comparing hte intrinsinc calibrations from matlab, ros and ours

**Comment by eupedrosa** [comment]
> We should have a subsection of results comparing hte intrinsinc calibrations from matlab, ros and ours

Yes, we should.
