### ISSUE TITLE
Decide which code formulation to use

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/AtlasCarCalibration#12]
After simlutaneously doing  #7, we need to define which code we are going to use, or if some hybrid. You make that decision. We must know this in order to continue the development in a sinlge code.

**Comment by miguelriemoliveira** [comment]
OK. Thanks.

**Comment by miguelriemoliveira** [comment]
Hi Afonso, I still see the python script **interactive_marker_test.py** .

After this issue we are focusing on developing only on **create_first_guess.py**, am I right?

If so, this should be deleted to avoid confusions. Git stores a copy in the previous versions, even if you delete the file.

**Comment by afonsocastro** [comment]
Yes, you're right. There's no more interactive_marker_test.py
