### ISSUE TITLE
and ... where's my camera?

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/AtlasCarCalibration#122]
Hi @eupedrosa ,

still about #115 , I do not draw the camera because there is no camera in the xacro file.

I see in the launch file that you launch a kinect frames publisher as a way to solve the problem, but we should have it on the xacro file.

You have an orbec astra right?

I looked around and found this:

https://github.com/turtlebot/turtlebot/tree/kinetic/turtlebot_description/urdf/sensors

Do you want me take care of this, or do you?

Thanks, 
Miguel

**Comment by eupedrosa** [comment]
Hi @miguelriemoliveira,
I will take care of this.

**Comment by miguelriemoliveira** [comment]
Thanks. If you need we have examples in the atlascar xacro, but I don't think you do.

**Comment by eupedrosa** [comment]
I added a mesh for the camera. Do not forget to update your local iris-ua/iris_ur10e repo.

**Comment by miguelriemoliveira** [comment]
Thanks @eupedrosa .
