### ISSUE TITLE
Unnecessary parameters data model in hand in eye

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/AtlasCarCalibration#123]
Hi @eupedrosa ,

I noticed you have the data model **parameters** . There is no need to have this, you could just optimize some of the transformations which are in the collections transforms data model.

That was the whole idea, not to have intermediate data structures just because of the optimization. I remember you said this was for you to learn and test the OptimizationUtils api.

Can I try to make a proposal for the simplification of your data models? Perhaps I could do a pull request, since it could be a big change ... what do you say?

Notice that this data model is not just unnecessary, it also contains duplicated information which  collides with the data in the transforms ..

**Comment by eupedrosa** [comment]
I understand your point. Make a proposal with a pull request.

**Comment by miguelriemoliveira** [comment]
Hi @eupedrosa ,

I am working on this. It was actually quite hard to make small changes and thus I have made my changes in a different file "eye_to_base_calib_miguel.py"

The good thing is that I used your idea of creating the parameters with the names of the transforms rather than the sensors (as discussed in #120 ).

Will give you more feedback tomorrow and then we can talk.



I still will cleanup and comment the code, so don't look at it for now.

We can then discuss how to fuse both proposals.

**Comment by miguelriemoliveira** [comment]
The visualization shows the camera in a strange place 

![image](https://user-images.githubusercontent.com/11350998/73487918-d58efb80-439f-11ea-936e-4b6445c207fe.png)


This is not where the camera is, right?

Should be some bug ...

**Comment by eupedrosa** [comment]
Yes, that looks like a bug. But the mesh is OK in the robot description.

**Comment by miguelriemoliveira** [comment]
Well but that was by the end of the optimization. At the start (i.e. before any optimization) the camera is here ... 


![image](https://user-images.githubusercontent.com/11350998/73532571-d746d680-4414-11ea-904e-fca62d04f41e.png)

![image](https://user-images.githubusercontent.com/11350998/73532585-e037a800-4414-11ea-8fad-e825d9bc25f8.png)

![image](https://user-images.githubusercontent.com/11350998/73532594-e88fe300-4414-11ea-8271-9cedfaf62fdd.png)

does it make sense?

**Comment by miguelriemoliveira** [comment]
Hi @eupedrosa ,

Here is the drawing of a calibrated camera ... 

![image](https://user-images.githubusercontent.com/11350998/73535912-9b177400-441c-11ea-8134-ed081805d49b.png)

And a video of the calibration process during the optimization ...

https://youtu.be/8tz4qkvfj88

Looks nice no? and the camera ends up in the place where it is mounted right?

**Comment by eupedrosa** [comment]
Very nice. The initial position is very far from the final position, did
you set that on purpose?

A sexta, 31 de jan de 2020, 12:35, Miguel Riem de Oliveira <
notifications@github.com> escreveu:

**Comment by miguelriemoliveira** [comment]
> Very nice. The initial position is very far from the final position, did
> you set that on purpose?

No, that was your first guess I think ... 

From what I understood from your code, the origin field here 

https://github.com/lardemua/AtlasCarCalibration/blob/master/interactive_calibration/calibrations/ur10e/eye_to_base/config.json

contains the translation and roll pith yaw angles of the first guess, to be used when we have a fixed sensor, right?

Can you give me a dataset with a non fixed patter dataset for me to test my code? Thanks.

**Comment by miguelriemoliveira** [comment]
I am closing this one. @eupedrosa , when you can please give me a non fixed pattern dataset.
