### ISSUE TITLE
Translate Ali et. al to our json format

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/AtlasCarCalibration#127]
Inverse problem is #114

**Comment by miguelriemoliveira** [comment]
Hi @eupedrosa ,

I have a first functional version. Instructions for using at 

https://github.com/lardemua/AtlasCarCalibration#convert-to-and-from-rwhe-datasets

Can you test and tell me if its working?

**Comment by eupedrosa** [comment]
It was almost working. I did the necessary changes. You can pull them.
The script only works for the dataset kuka_1, am I right?

**Comment by miguelriemoliveira** [comment]
Hi @eupedrosa ,

great that its working. 

I did not not test it but I would say it should work with the other kuka-chessboard datasets.

For other datasets if they have different cameras or patterns you must create a new 

interactive_calibration/calibrations/rwhe_kuka/config.json

for that purpose. 

but I think its pretty general ... 

Should I close the issue? Do you need anything else?

**Comment by eupedrosa** [comment]
I think you can close the issue. I was able to generate kuka_2 and kuka_3.
