### ISSUE TITLE
Small improvement to the optimization.

### ISSUE THREAD

**Issue by eupedrosa** [lardemua/AtlasCarCalibration#134]
@miguelriemoliveira, I did a small change in the objective function and now the optimization takes 12.899 seconds for the both-eyes dataset  instead of 16.431 seconds. We also have an improvement in the errors.

![both-eyes_(old)_rmse](https://user-images.githubusercontent.com/6196901/76115716-95dfb300-5fe0-11ea-8155-2e50569724e5.png)
![both-eyes_(new)_rmse](https://user-images.githubusercontent.com/6196901/76115802-be67ad00-5fe0-11ea-8840-575d84d98308.png)

![both-eyes_(old)_proj](https://user-images.githubusercontent.com/6196901/76115723-9a0bd080-5fe0-11ea-94b1-3c6c7a9ebfc1.png)
![both-eyes_(new)_proj](https://user-images.githubusercontent.com/6196901/76115873-d5a69a80-5fe0-11ea-917d-e9fd9ae143d0.png)

**Comment by miguelriemoliveira** [comment]
I @eupedrosa ,

I will close this issue, but the images look really nice. I did not remember how nice they looked. Don't forget to add some in our paper.
