### ISSUE TITLE
Create dataset translator for tabb et al

### ISSUE THREAD

**Issue by eupedrosa** [lardemua/AtlasCarCalibration#135]
code: https://github.com/amy-tabb/RWHEC-Tabb-AhmadYousef

dataset: https://data.nal.usda.gov/dataset/data-solving-robot-world-hand-eyes-calibration-problem-iterative-methods

**Comment by miguelriemoliveira** [comment]
I think I got the first version working ... here's the dataset.json for hte DS7

https://jsoneditoronline.org/#left=local.yotigu&right=local.xivasu

I tested with DS1 and with DS7 and it seems to be working. 

This one takes more time since we calibrate the sensors intrinsics everytime the script is called.

How to call for DS1

```bash
rosrun interactive_calibration convert_from_tabb_dataset.py -ds /home/mike/datasets/tabb/DS1/ -out /home/mike/datasets/DS1_converted -json /home/mike/catkin_ws/src/AtlasCarCalibration/interactive_calibration/calibrations/tabb/ds1.json
```

and for DS7

```bash
rosrun interactive_calibration convert_from_tabb_dataset.py -ds /home/mike/datasets/tabb/DS7/ -out /home/mike/datasets/DS7_converted -json /home/mike/catkin_ws/src/AtlasCarCalibration/interactive_calibration/calibrations/tabb/ds7.json
```

**Comment by miguelriemoliveira** [comment]
@eupedrosa , I think it is working, please try it out. 

I will do the opposite conversion later on ...

**Comment by eupedrosa** [comment]
Nice.. I'm gonna test it.

**Comment by eupedrosa** [comment]
It is not working, it does not converge to a solution. I'm still investigating why. Maybe a bad first guess? Or something in the data import?

**Comment by miguelriemoliveira** [comment]
Hi Eurico.

Could be something  in the conversion.

There was no first guess so I just put 0 0 0 0 0 0 for x y z r p y.


Tell me how I can help.

**Comment by eupedrosa** [comment]
I think I solved it.
The transformation had to be inverted and the translation were in milimeters.

**Comment by miguelriemoliveira** [comment]
Great!

**Comment by eupedrosa** [comment]
The Tabb dataset is, in my opinion, not great. It has no rotations and most of the views are perpendicular to the pattern plane (i.e. ccd and and patern plane are parallel). This is specially noticeable when optimizing the intrinsic parameters and I get a value of 30 to the skew and the orientation of the sensor is compensated for this. This means that there is a degree of freedom that is neglected by this dataset.

@miguelriemoliveira, what is opinion about this?

**Comment by miguelriemoliveira** [comment]
Startting to work to the inverse process of translation ...

**Comment by miguelriemoliveira** [comment]
> The Tabb dataset is, in my opinion, not great. It has no rotations and most of the views are perpendicular to the pattern plane (i.e. ccd and and patern plane are parallel). This is specially noticeable when optimizing the intrinsic parameters and I get a value of 30 to the skew and the orientation of the sensor is compensated for this. This means that there is a degree of freedom that is neglected by this dataset.
> 
> @miguelriemoliveira, what is opinion about this?

I agree with what you say.

**Comment by miguelriemoliveira** [comment]
Hi @eupedrosa ,

I have a convert_to_tabb script functional. Can you test it?

Instruction on how to use here:

https://github.com/lardemua/AtlasCarCalibration#to-convert-to-an-tabb-dataset-run

Be careful about this note:

https://github.com/lardemua/AtlasCarCalibration/blob/16f3622d2698829e0419c28f30643e06c1f71389/interactive_calibration/scripts/convert_to_tabb_dataset.py#L113-L114

Tell me if it works.

**Comment by miguelriemoliveira** [comment]
Hi @eupedrosa 

this is working right? Should we close?

**Comment by eupedrosa** [comment]
Yes, we can close.
