### ISSUE TITLE
Create labelling procedure for 3D LiDAR scans

### ISSUE THREAD

**Issue by aaguiar96** [lardemua/AtlasCarCalibration#139]

**Comment by miguelriemoliveira** [comment]
Start with a standalone python code that isolates the points from the pattern board using ransac on the point cloud (or a subset of it)

Ransac in python can be taken from 
https://github.com/miguelriemoliveira/RansacPlaneDetection

**Comment by aaguiar96** [comment]
Hi @miguelriemoliveira  and @eupedrosa 

I created a standalone repo so that you can follow the code.
You can find it [here](https://github.com/aaguiar96/3DScanLabeler).

I've written the PCL callback today, and now I'll start the algorithm itself. :)

**Comment by miguelriemoliveira** [comment]
Hi André,

when I said standalone I means a standalone file. It did not have to be an
entirely new repository,

In any case, the important thing is that you are moving forward!

Regards,
Miguel
*  Miguel Riem de Oliveira                                             *
email:    mriem@ua.pt    |    m.riem.oliveira@gmail.com
office: 22.2.18                 |    ext: 23887
Dep. de Engenharia Mecânica, Universidade de Aveiro
*Campus Universitário de Santiago, 3810-193  Portugal*

**Comment by aaguiar96** [comment]
Hi @miguelriemoliveira and @eupedrosa 

I think RANSAC works... :) 

![plane](https://user-images.githubusercontent.com/35901587/80090052-d2e31300-8556-11ea-8669-5e2a5c0eaf0a.png)
![plane1](https://user-images.githubusercontent.com/35901587/80090054-d4144000-8556-11ea-8f84-708c76c9a187.png)

**Comment by aaguiar96** [comment]
Now, my idea is to:

- Validate the results more extensivelly
- Use the `Publish Point` of Rviz to set the seed point (now I'm setting it on the code)
- Trank the chessboard points frame-by-frame

What do you think?

**Comment by miguelriemoliveira** [comment]
Great! Looks good. But I think now is the time to integrate with the data_collector and labellor

Because the second functionality we have it already implemented ...

Not sure what's best, but I think this may be a good time to start integrating ... If you want we can meet and I guide you through the process.

**Comment by aaguiar96** [comment]
Ok, sure. 
We can integrate and then implement the missing features.

Ok Miguel, we can meet. I'll send you an e-mail.

**Comment by aaguiar96** [comment]
I think I found a solution much simpler than RANSAC.
Just selecting the middle point of the chessboard on the initialization, and then tracking it gives a great result.
In the gif, the white points are the points estimated to be on the chessboard, and the big white point is the seed point, resulting from the tracking.

![output](https://user-images.githubusercontent.com/35901587/80121643-7c8cc900-8584-11ea-9ff9-9e8ffe589913.gif)

On the contrary, RANSAC is failing to estimate the chessboard plane in many iterations and considers the person body in a lot of them to...
Of course, it could be possible to refine the RANSAC solution since it is more elegant.

**Comment by eupedrosa** [comment]
There are a few points in white that belong to the user, they are _unwanted_.

> For example, we can feed the RANSAC only with these points to eliminate some outliers that might appear.

This may work.

**Comment by miguelriemoliveira** [comment]
Hi @aaguiar96 ,

results look really nice. I think @eupedrosa  is right about doing ransac as a post processing to refine the results.

I did not really understand how you did the tracking part:

> Just selecting the middle point of the chessboard on the initialization, and then tracking it gives a great result.
> In the gif, the white points are the points estimated to be on the chessboard, and the big white point is the seed point, resulting from the tracking.

Can you give more details? I am interested.

**Comment by aaguiar96** [comment]
> Can you give more details? I am interested.

Since RANSAC was not working as well as expected, I tried out a simple tracking approach.
So, the user initializes the system selecting a point on the chessboard (close to the middle one preferably).
Then, the chessboard is clustered using its approximate real size.
The tracking is done computing the seed point in each iteration by the average of all points in the cluster. :+1:

**Comment by aaguiar96** [comment]
> For example, we can feed the RANSAC only with these points to eliminate some outliers that might appear.

Ok, I think this approach is working.
I was having problems with RANSAC because I forgot to reset the number of inliers to 0 before starting RANSAC, for each frame received. Also, I added the feature of checking if the three selected points are colinear.

This is the result with `distance_threshold = 0.02` and 100 iterations, feeding the RANSAC only with the tracked points.

![output](https://user-images.githubusercontent.com/35901587/80213875-c4b5f500-8631-11ea-871e-870d6f34abea.gif)

Do you think is good enough or still can be improved?

**Comment by miguelriemoliveira** [comment]
Hi  @aaguiar96 ,

it looks really nice. I would say lets try with this one and then if we need a more accurate detection we revisit the problem. 

For now I would say we need to integrate with the collect_and_label script (on me for now, #141) .

Then, the goal is to generate a dataset from the agrob bagfile. I would close this one and work on #141 from now on ...

**Comment by aaguiar96** [comment]
> One question: you did a new feature which sounds nice. It should be integrated into https://github.com/miguelriemoliveira/RansacPlaneDetection
> I will add you as a collaborator, can you push?

Yes sure @miguelriemoliveira 



> For now I would say we need to integrate with the collect_and_label script (on me for now, #141) .

Ok, I agree.
I'll close the issue then. Thanks for the support @miguelriemoliveira
