### ISSUE TITLE
Add Agrob description to playback launch file

### ISSUE THREAD

**Issue by aaguiar96** [lardemua/AtlasCarCalibration#140]

**Comment by miguelriemoliveira** [comment]
The file is there as a copy of another calibration ... you must change it now.

**Comment by aaguiar96** [comment]
@miguelriemoliveira should I also place the agrob xacro description on `AtlasCarCalibration/interactive_calibration/urdf/` folder and load it from the launch file?

**Comment by miguelriemoliveira** [comment]
Hi André,

Take the atlascar as an example. I think the xacros should be in your
robot's package.

in the atlascar the xacro files are in the atlascar2 folder.

Hope it helps,
Miguel
*  Miguel Riem de Oliveira                                             *
email:    mriem@ua.pt    |    m.riem.oliveira@gmail.com
office: 22.2.18                 |    ext: 23887
Dep. de Engenharia Mecânica, Universidade de Aveiro
*Campus Universitário de Santiago, 3810-193  Portugal*

**Comment by aaguiar96** [comment]
Hi @miguelriemoliveira and @eupedrosa 

I think it is done, you can check it.
The only difference to atlascar2 was that the velodyne PCL, when recorded, was on the `/velodyne` referential frame, and the `urdf` generates a link with the name `vlp16_frame`. So, I had to add a static dummy link from `/vlp16_frame` to `/velodyne` so that the PCL can be visualized on Rviz without the tf's generated by the bagfile.

**Comment by aaguiar96** [comment]
Hi @miguelriemoliveira and @eupedrosa 

I think it is done, you can check it.
The only difference to atlascar2 was that the velodyne PCL, when recorded, was on the `/velodyne` referential frame, and the `urdf` generates a link with the name `vlp16_frame`. So, I had to add a static dummy link from `/vlp16_frame` to `/velodyne` so that the PCL can be visualized on Rviz without the tf's generated by the bagfile.

**Comment by aaguiar96** [comment]
Also, I've already written the `config.json` file for agrob.
I leave here the tf tree generated by the agrob `xacro`.

![frames](https://user-images.githubusercontent.com/35901587/79890202-10308f00-83f7-11ea-97dc-66e1b38a86f0.png)

**Comment by miguelriemoliveira** [comment]
Hi @aaguiar96 ,

I am in my teaching inferno. Will only be over tomorrow by the end of the afternoon.

I will take a look on Thursday.

**Comment by miguelriemoliveira** [comment]
Great! I will take a look on Thursday.

See you,Miguel

*  Miguel Riem de Oliveira                                             *
email:    mriem@ua.pt    |    m.riem.oliveira@gmail.com
office: 22.2.18                 |    ext: 23887
Dep. de Engenharia Mecânica, Universidade de Aveiro
*Campus Universitário de Santiago, 3810-193  Portugal*

**Comment by miguelriemoliveira** [comment]
Hi @aaguiar96 

> So, I had to add a static dummy link from /vlp16_frame to /velodyne 

and you do this in the xacro?

**Comment by aaguiar96** [comment]
> Hi @aaguiar96
> 
> > So, I had to add a static dummy link from /vlp16_frame to /velodyne
> 
> and you do this in the xacro? Or with a static_transform_publisher?

I've done it with static_transform_publisher.

**Comment by aaguiar96** [comment]
@miguelriemoliveira, I think we can close this one too. What do you think?

**Comment by miguelriemoliveira** [comment]
Hi @aaguiar96 ,

we tested today and it seems to be working. 

Problems to solve in the next bag file:

1. camera_info topic matching the image topic
2. velodyne lidar reference frame

**Comment by miguelriemoliveira** [comment]
Telepathy :)
