### ISSUE TITLE
Need a bagfile

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/AtlasCarCalibration#143]
Hi @eupedrosa ,

for the paper, I wanted to run the bagfile to record videos and save snapshots.

I only have the datasets, which means I cannot show for example the interactive sensor positioning.

Can you send the bagfiles to me? If possible send me both use cases (and also the both-eyes), since I am thinking of having a video for each.

Thanks,
Miguel

**Comment by eupedrosa** [comment]
Ok, pay attention to you email. I will send them to you during the afternoon.

**Comment by miguelriemoliveira** [comment]
OK, thanks.

**Comment by miguelriemoliveira** [comment]
Just finished downloading. Thanks @eupedrosa .
