### ISSUE TITLE
Show agrob decription during the optimization procedure

### ISSUE THREAD

**Issue by aaguiar96** [lardemua/AtlasCarCalibration#148]

**Comment by miguelriemoliveira** [comment]
I am on it.

**Comment by aaguiar96** [comment]
Thanks Miguel! Starting to work on this again tomorrow! :)

**Comment by miguelriemoliveira** [comment]
Ok, we can talk if you want, but I will be busy from 16h onward, so it has to be before.

**Comment by aaguiar96** [comment]
I'll try to develop the cost function in the morning. We can talk at 15h if you want.

**Comment by miguelriemoliveira** [comment]
ok.

See you tomorrow.

Miguel

*  Miguel Riem de Oliveira                                             *
email:    mriem@ua.pt    |    m.riem.oliveira@gmail.com
office: 22.2.18                 |    ext: 23887
Dep. de Engenharia Mecânica, Universidade de Aveiro
*Campus Universitário de Santiago, 3810-193  Portugal*

**Comment by miguelriemoliveira** [comment]
Working on it ... it is already shows the robot but we still havea lot of loose ends ... tomorrow .

![image](https://user-images.githubusercontent.com/11350998/81518489-21a1f280-9336-11ea-9647-421b9b1aac56.png)

**Comment by miguelriemoliveira** [comment]
OK, so now we are drawing the velodyne points. Here's an image:

![image](https://user-images.githubusercontent.com/11350998/81622008-d0523b80-93e7-11ea-8ec0-95f723e5b9ae.png)

**Comment by miguelriemoliveira** [comment]
Tomorrow I will try to check why the chessboard is not being drawn.

**Comment by miguelriemoliveira** [comment]
Ok, so now we have the chessboard. The visualization.py can be generalized to be the same for all calibration cases. However to undertake this endeavour, I will need a bagfile with some collections, cameras, 3D lidar and also 2D lidars. Need to have everything to then test the visualization.

@aaguiar96 would it be possible to have also in the next agorb bagfile also the 2D sick lidar data? That way we could use agrob as the testbed that has everything ... and we would also calibrate that one ...

For now this will wait for a better bagfile to continute development.

**Comment by aaguiar96** [comment]
> Ok, so now we have the chessboard. The visualization.py can be generalized to be the same for all calibration cases. However to undertake this endeavour, I will need a bagfile with some collections, cameras, 3D lidar and also 2D lidars. Need to have everything to then test the visualization.

Nice @miguelriemoliveira  :)



> @aaguiar96 would it be possible to have also in the next agorb bagfile also the 2D sick lidar data? That way we could use agrob as the testbed that has everything ... and we would also calibrate that one ...

Hum... We do not have any planar laser available at this moment in agrob. Velodyne can work with a single ring, emulating a planar laser, but I think you need that from different sources right?

**Comment by miguelriemoliveira** [comment]
Yes, different sensors would be better. Even to emulate all the stuff with the ros 2D lidar drivers.

I remembered before you had a yellow sick, that's why I asked.

Lets proceed with the velodyne and the zed cameras only. 

I will try to develop a general visualization code testing different bags.

**Comment by aaguiar96** [comment]
Ok @miguelriemoliveira, sounds great.
I'll work on the cost function. I let you know as soon as I have new results.

Also, I'll call Tania Barbosa on Monday. :)

**Comment by miguelriemoliveira** [comment]
Ok, look, I saw your code running. I think your cost function is well implemented (the beam error is being propoperly optimized, I think). 

The problem is, we may have to increase the complexity of the cost function. When you are available, let's chat for a moment.

**Comment by aaguiar96** [comment]
I @miguelriemoliveira 

I was looking for it right now. I can't find any bug...
I have half an hour free now. Let's meet?

**Comment by eupedrosa** [comment]
If you want, I can also participate (@miguelriemoliveira, @aaguiar96)

**Comment by miguelriemoliveira** [comment]
Hi @eupedrosa 

only now I saw this. Sorry. I said to @aaguiar96 to try to implement the border distance metric.

**Comment by eupedrosa** [comment]
So.. you did not want my participation :cry:

> only now I saw this. Sorry. I said to @aaguiar96 to try to implement the border distance metric

:+1:

**Comment by miguelriemoliveira** [comment]
: - )

**Comment by aaguiar96** [comment]
> If you want, I can also participate (@miguelriemoliveira, @aaguiar96)

Sorry @eupedrosa, I only saw it now too... :D

**Comment by miguelriemoliveira** [comment]
Work on this will proceed in a general fashion for all robotic systems. 

Further developments on #156
