### ISSUE TITLE
Dangerous piece of code

### ISSUE THREAD

**Issue by eupedrosa** [lardemua/AtlasCarCalibration#38]
```python
class DataCollectorAndLabeler:
    def __init__(self, world_link, output_folder, server, menu_handler, marker_size, chess_numx, chess_numy):
        if os.path.exists(output_folder):
                shutil.rmtree(output_folder)  # Delete old folder
```

What would you do if a third party software did this on your computer without explicit permission? :thinking:

**Comment by miguelriemoliveira** [comment]
I think this is the one which erased @Afonso Castro <afonsocastro@ua.pt>
's desktop stuff already two times.

Can you insert at least a question like "this is dangerous, would you like
to continue"

Thanks,
Miguel
*  Miguel Riem de Oliveira                                             *
email:    mriem@ua.pt    |    m.riem.oliveira@gmail.com
Dep. de Engenharia Mecânica, Universidade de Aveiro
*Campus Universitário de Santiago, 3810-193  Portugal*
