### ISSUE TITLE
Note on github about installing flycap

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/AtlasCarCalibration#39]
Hi @afonsocastro, (@tiagomfmadeira , @eupedrosa )

flycap is needed for this package to compile. Add a note on the readme about that please.

**Comment by afonsocastro** [comment]
Done, but not tested yet. Today we meet?

**Comment by miguelriemoliveira** [comment]
Yes, at 9h30.


*  Miguel Riem de Oliveira                                             *
email:    mriem@ua.pt    |    m.riem.oliveira@gmail.com
Dep. de Engenharia Mecânica, Universidade de Aveiro
*Campus Universitário de Santiago, 3810-193  Portugal*

**Comment by miguelriemoliveira** [comment]
Thanks.
