### ISSUE TITLE
Collect a bag file with the UR10 for calibrating camera w.r.t. robot

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/AtlasCarCalibration#42]

**Comment by eupedrosa** [comment]
First bag created. Here is a single image.

![example](https://user-images.githubusercontent.com/6196901/68483705-f37f1100-0233-11ea-8512-bb36db7b3b3a.png)

Do you think that this kinda of data will be enough? The light conditions are not the best.

**Comment by miguelriemoliveira** [comment]
It looks good. I think it looks fine, but the only way to know is to see if the checkerboard is detected in the images.

We use this line to perform the detection:

https://github.com/lardemua/AtlasCarCalibration/blob/a652897ec55d63126fabc8a13d822cef120f0870/interactive_calibration/src/interactive_calibration/interactive_data_labeler.py#L231

Perhaps you can create a simple test script with receives an image  filename as input  (or a topic name) and shows the image with the detection overlayed? ...

If you want I can try to do that ...

Did you start with a description of the robot already? You could add a folder in https://github.com/lardemua/AtlasCarCalibration/tree/master/interactive_calibration/calibrations
with "your robot".

**Comment by eupedrosa** [comment]
> Perhaps you can create a simple test script with receives an image filename as input (or a topic name) and shows the image with the detection overlayed? ...

I will do this!! I will add the script to the interaction_calibration for future use.
> Did you start with a description of the robot already?

Yes!!. And I will add the xacros to "my robot".

**Comment by miguelriemoliveira** [comment]
Great. Push when you can. I am eager to take a look!

**Comment by eupedrosa** [comment]
Here we have good example:
![good_chess](https://user-images.githubusercontent.com/6196901/68487404-ec0f3600-023a-11ea-8c9b-2ed6726cdfb4.png)

And here we have a bad example:
![bad_chess](https://user-images.githubusercontent.com/6196901/68487435-faf5e880-023a-11ea-82e1-b39462854a98.png)

I think that I'm going to create a new bag with this utility window opened :smiley:

**Comment by miguelriemoliveira** [comment]
the utility is already becoming useful :)

**Comment by miguelriemoliveira** [comment]
Hi @eupedrosa I was looking at the images you have in the video and thinking that you'll need also images with the chessboard rolled and pitched, as in an intrinsic calibration.

**Comment by miguelriemoliveira** [comment]
This is done, right?

**Comment by eupedrosa** [comment]
Yes. This can be closed.
