### ISSUE TITLE
Tracking of chessboard in 3D

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/AtlasCarCalibration#44]
To use the asus xtion check https://wiki.ros.org/openni2_launch

**Comment by miguelriemoliveira** [comment]
First step is done. @tiagomfmadeira can already cluster the point clouds ...

**Comment by tiagomfmadeira** [comment]
Here is the result using Open3D's _cluster_dbscan_

![Screenshot from 2019-11-12 11-15-58](https://user-images.githubusercontent.com/15963210/68667569-34ca3600-053e-11ea-827c-1d4ce4d36a98.png)

**Comment by tiagomfmadeira** [comment]
I have integrated the previously described method of clustering with the rest of the implementation. 
It is now possible to read the clouds from the **/camera/depth/points** topic, extract the clusters, and publish a colored portion of the cloud in /camera/depth/points/labeled.
However, the clustering seems to be too slow, at least with the parameters I'm currently experimenting with... Will look into the clustering method again.

![Screenshot from 2019-11-18 22-15-06](https://user-images.githubusercontent.com/15963210/69099273-45a10d00-0a52-11ea-9304-65d9112aca39.png)

**Comment by miguelriemoliveira** [comment]
Great news! It looks great. The problem of being to slow, can you quantify, how many hz?

We had the idea of clustering in the image space, we could go into that ...

**Comment by tiagomfmadeira** [comment]
Attempting a 2D approach to the clustering for optimization purposes using FloodFill and image contours.
![Screenshot from 2019-11-26 16-39-43](https://user-images.githubusercontent.com/15963210/69802028-83c7ca80-11d0-11ea-8466-b3b799442078.png)

**Comment by miguelriemoliveira** [comment]
Hi @tiagomfmadeira ,

about the part of the calibration config json 

 ```json
"top_center_rgbd_camera_depth_frame": {
           "link": "top_center_rgbd_camera_depth_optical_frame",
           "parent_link": "top_center_rgbd_camera_link",
           "child_link": "top_center_rgbd_camera_depth_frame",
           "topic_name": "/top_center_rgbd_camera/depth/points"
        }
```

I would suggest to put the name **top_center_rgbd_camera_depth_frame** to **top_center_rgbd_camera_depth** since it is the name of the sensor.

**Comment by miguelriemoliveira** [comment]
Hi again @tiagomfmadeira ,

reviewing your code ... this 

https://github.com/lardemua/AtlasCarCalibration/blob/de74c5f561d7d3cfb68a93008437efd6acc2b76a/interactive_calibration/src/interactive_calibration/interactive_data_labeler.py#L344

looks strange since a depth image should be floar or 16C1, but not 8C1

**Comment by miguelriemoliveira** [comment]
http://docs.ros.org/kinetic/api/image_geometry/html/python/index.html

**Comment by miguelriemoliveira** [comment]
rospy get param https://wiki.ros.org/rospy_tutorials/Tutorials/Parameters#Getting.2C_Setting.2C_and_Deleting_Parameters

**Comment by miguelriemoliveira** [comment]
Complete. Will continue to work on #117.
