### ISSUE TITLE
Create a -configuration_file command line parameter

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/AtlasCarCalibration#46]
This would be useful to avoid a lot of command line arguments. We could use a json config file instead.

**Comment by miguelriemoliveira** [comment]
Hi @eupedrosa 

aparently this is off-the-shelf with argparse, the library we're using

https://stackoverflow.com/questions/3609852/which-is-the-best-way-to-allow-configuration-options-be-overridden-at-the-comman

**Comment by eupedrosa** [comment]
I Will take a look at it.

**Comment by miguelriemoliveira** [comment]
After #53 which pushed some parameters into the calibration configuration file, this is not relevant anymore.
