### ISSUE TITLE
How to configure catkin build

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/AtlasCarCalibration#48]
Hi @eupedrosa ,

can you tell me what must be done to configure catkin build?

Thanks,
Miguel

**Comment by miguelriemoliveira** [comment]
I remember you configured something with /opt/ros ...

**Comment by eupedrosa** [comment]
I will leave here the full steps:

### Install
```$ sudo apt install python-catkin-tools```
### First use
In the topmost directory of your code, i.e. the one that has a `src` directory, execute
```
$ catkin configure --extend /opt/ros/melodic
$ catkin build
$ source devel/setup.bash
```
### Onward 
```
$ source devel/setup.bash
```

**Comment by miguelriemoliveira** [comment]
Thanks!

**Comment by miguelriemoliveira** [comment]
BTW, this 

> catkin configure --extend /opt/ros/melodic

should be:

> catkin config --extend /opt/ros/melodic

**Comment by eupedrosa** [comment]
Sorry, I wrote it from memory!
