### ISSUE TITLE
Better 3D plotting?

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/AtlasCarCalibration#50]
Hi @afonsocastro , @tiagomfmadeira and @eupedrosa ,

we are using matplotlib for drawing the 3D graphs, but the quality of the figures is not very good.
Here's an example:

![Screenshot at 2019-11-13 02-31-41](https://user-images.githubusercontent.com/11350998/68729071-e90ca080-05c0-11ea-951f-d8ee080e8b68.png)

I looked around and found [this](https://docs.enthought.com/mayavi/mayavi/auto/examples.html)

do you know any good alternatives for 3D plotting with python?

**Comment by miguelriemoliveira** [comment]
here's another interesting one
https://plot.ly/python/#3d-charts

**Comment by eupedrosa** [comment]
[Plotly](https://plot.ly/)  looks interesting :+1:
Do you want to test it, @miguelriemoliveira ?

**Comment by miguelriemoliveira** [comment]
I am on it ...

**Comment by miguelriemoliveira** [comment]
So I tried to dive into plotly but could not as of now find a way to update a graph as we need in our application. I posted a question in the forum, lets see...

**Comment by miguelriemoliveira** [comment]
After discussion with @eupedrosa and @afonsocastro we decided the best and fastest way to go is to use rviz. Will work on it.

**Comment by miguelriemoliveira** [comment]
Made some progress. Right now I am showing the car and sensor models, the tfs, the images and the laser data. Here's an example:

https://youtu.be/M22ZAQuAusw

Will include the chessboards and other inportant features in the near future.

**Comment by miguelriemoliveira** [comment]
Now we are drawing the chessboards for each collection ...

![image](https://user-images.githubusercontent.com/11350998/69539028-939aa100-0f7b-11ea-9dcd-0f6e056d6a56.png)

**Comment by eupedrosa** [comment]
:+1: nice
