### ISSUE TITLE
Add parent and child link information to transforms in json file

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/AtlasCarCalibration#54]
It would be useful to pulish back the transforms to ROS...

![image](https://user-images.githubusercontent.com/11350998/69441124-fe609800-0d41-11ea-934d-6eddd70d96ca.png)

**Comment by eupedrosa** [comment]
You want the full **tf** tree?

**Comment by miguelriemoliveira** [comment]
We have it already, but the parent and child links were not there. I am currently deducing them from the transform name, but it is best to have this information explicit.
