### ISSUE TITLE
Location, location, location...

### ISSUE THREAD

**Issue by eupedrosa** [lardemua/AtlasCarCalibration#57]
In which package should I put an the *arm_and_camera* optimization problem? In the `OptimizationUtils`  or  `interactive_calibration`?
Being a calibration problem, I think that is should go to the `interactive_calibration` package. What is your opinion?

**Comment by miguelriemoliveira** [comment]
Yes, you are doing a code which is parallel to the
https://github.com/miguelriemoliveira/OptimizationUtils/tree/master/test/sensor_pose_json_v2
folder

Regards,
Miguel

*  Miguel Riem de Oliveira                                             *
email:    mriem@ua.pt    |    m.riem.oliveira@gmail.com
Dep. de Engenharia Mecânica, Universidade de Aveiro
*Campus Universitário de Santiago, 3810-193  Portugal*

**Comment by miguelriemoliveira** [comment]
We talked about this today.
