### ISSUE TITLE
New bag file of the ATLASCAR2

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/AtlasCarCalibration#68]
If possible we should include 3d cameras already mounted. Talk to João Figueiredo.about the intel real sense

Talk to @tiagomfmadeira about asus xtion

T

**Comment by miguelriemoliveira** [comment]
Hi @afonsocastro , don't forget to commit the new xacro. 

It should go to the atlas2-description , right?

**Comment by miguelriemoliveira** [comment]
Here is a xacro of an asus xtion to copy from ...

https://github.com/tu-darmstadt-ros-pkg/hector_models/blob/kinetic-devel/hector_sensors_description/urdf/asus_camera.urdf.xacro

**Comment by miguelriemoliveira** [comment]
and the video from @eupedrosa I told you about is on issue #70, it is really nice.

**Comment by afonsocastro** [comment]
`rosrun rqt_bag rqt_bag` to cut a big bagfile

**Comment by afonsocastro** [comment]
created
