### ISSUE TITLE
Reorganize code to make it easier to make changes ...

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/AtlasCarCalibration#7]

**Comment by miguelriemoliveira** [comment]
Hi @afonsocastro ,

I tried to reorganize your code to make it easier for future changes. Take a look and see if you agree with the changes. We can discuss afterwards.

**Comment by miguelriemoliveira** [comment]
Did you just commit?

I was just about to do a push as well ...

**Comment by miguelriemoliveira** [comment]
and we were doing exactly the same thing ... damn. Well, I will send you my code by email. If you agree with it I can merge you your code later ...

**Comment by afonsocastro** [comment]
what a coincidence! I commited yes, I'll see your code now.
