### ISSUE TITLE
Chessboard detection is not invariant to orientation.

### ISSUE THREAD

**Issue by eupedrosa** [lardemua/AtlasCarCalibration#70]
I noticed that, while collecting data, the chessboard detection can have different orientations. Look at the bottom right of the images:
![collect0](https://user-images.githubusercontent.com/6196901/69870722-b93fe700-12a8-11ea-8a3c-c2e1bc32b6b2.png)

![collect1](https://user-images.githubusercontent.com/6196901/69870743-c8269980-12a8-11ea-9a08-ee136f3fa8b7.png)

Is this something that you are aware of?

**Comment by miguelriemoliveira** [comment]
I was aware of this and this is a problem: if it happens on the dataset it will ruin your calibration (intrisinc, extrinsic, whatever).

We have a calibration pattern with oddxeven number of corners. This I think makes the detection more robust to these situations. 

However, whenever we note this occurs, we just thrash the dataset and start a new one.

@afonsocastro  you should also be carefull with this when doing #68

**Comment by miguelriemoliveira** [comment]
@eupedrosa is your chessboard odd x even (or  even x odd) or is it even x even (or odd x odd)?

**Comment by eupedrosa** [comment]
It is a odd x odd chessboard. Do I have to change it? I think I can try to solve this with software!!!!

**Comment by miguelriemoliveira** [comment]
Changing it will improve I think  but I am not sure it will solve the whole problem.

Solving with software is cumbersome since you would have to make some kind of assumption which is not general and, furthermore, you would have to add this new software to the opencv chessboard detection code, and ask for a pull request.

If you say solve with software only for our calibration (which means you compute the intrinsics with another dataset where this phenomenon does not occur), we could do that ...

How often do you have this issue? I mean, we just do not collect data when the chessboards are not well detected ...

**Comment by eupedrosa** [comment]
It happens way to often.
I solved it with a *hack*. It is not very ugly. It adds 3 lines of code and 1 line change. However, it adds the assumptions that the chessboard will maintain an angle bellow 90 degrees. Is this bad?

**Comment by miguelriemoliveira** [comment]
Where is this hack located?

**Comment by miguelriemoliveira** [comment]
I like the "not very ugly" expression ...

**Comment by eupedrosa** [comment]
The hack is located at `interactive_data_label.py`.
Check line 232
```python
           # Find chessboard corners
            self.found, corners = cv2.findChessboardCorners(image_gray, (self.numx, self.numy))
            if not self.found:
                cv2.drawChessboardCorners(image, (self.numx, self.numy), corners, self.found)  # Draw and display the corners

            if self.found is True:
                diff = corners[0][0][0] - corners[self.numx-1][0][0]
                if diff > 0:
                    corners = corners[::-1]

                cv2.drawChessboardCorners(image, (self.numx, self.numy), corners, self.found)  # Draw and display the corners

                # print('Found chessboard for ' + self.name)
                criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
                corners2 = cv2.cornerSubPix(image_gray, np.array(corners), (self.numx, self.numy), (-1, -1), criteria)
                corners2_d = []
```
It just verifies the x coordinate difference between the first corner and the last corner in the same row.
If the difference is positive it means that it is flipped. I just reverse the corner array.

**Comment by miguelriemoliveira** [comment]
It looks great. Does it work? Is the drawing rotated back to the propper place? Do you think it may have problems in other scenarios?

If it works my opinion is to include it. I would just recomend you do a ros warn every time you do this, to notify the user we are doing it.

**Comment by eupedrosa** [comment]
Yes, it draws the chessboard in the proper place. I do not thing it may cause any problem beyond the one that I already mention. The ROS warn is a good idea. I will test it a little bit more.

**Comment by miguelriemoliveira** [comment]
Sounds great. Can you post some images showing you solved the problem of
the images you posted prevuously?

A Sex, 29/11/2019, 14:40, Eurico F. Pedrosa <notifications@github.com>
escreveu:

**Comment by eupedrosa** [comment]
I give you moving images (without the hack and with the hack)
![not_reversed](https://user-images.githubusercontent.com/6196901/69879112-87d21600-12be-11ea-9df5-f3918cfbac2b.gif) ![reversed](https://user-images.githubusercontent.com/6196901/69879125-91f41480-12be-11ea-9146-07228046dd7a.gif)

Not synchronized but..

**Comment by miguelriemoliveira** [comment]
This is really nice, gifs. I got to do that as well. 

Not syncronized ... booo !

**Comment by miguelriemoliveira** [comment]
:+1:

**Comment by miguelriemoliveira** [comment]
Reopenning, the commit should close the issue ...

**Comment by miguelriemoliveira** [comment]
Hi @eupedrosa ,

Just remembered we also will have this problem in 

https://github.com/miguelriemoliveira/OptimizationUtils/blob/20058582f784469088dd621f61e55c97d6307ef8/test/sensor_pose_json_v2/chessboard.py#L227

Actually, the idea already in a json there was not to redetect the chessboard but to use the corners from the initial detection contained in the json.

@eupedrosa can you do this with @afonsocastro 's help?

**Comment by miguelriemoliveira** [comment]
@eupedrosa  and @afonsocastro , just did it what I suggested above. Closing issue.
