### ISSUE TITLE
Data collector not saving the data that is labelled

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/AtlasCarCalibration#72]
This is a big bug. When looking at the 

https://github.com/lardemua/AtlasCarCalibration/blob/6264bec39e22645006f33b4346872adada4a1ef4/interactive_calibration/src/interactive_calibration/data_collector_and_labeler.py#L137

in particular 

https://github.com/lardemua/AtlasCarCalibration/blob/6264bec39e22645006f33b4346872adada4a1ef4/interactive_calibration/src/interactive_calibration/data_collector_and_labeler.py#L151

I noticed that we were actually saving sensor data received in messages that were not labelled, since the labelling occurs here

https://github.com/lardemua/AtlasCarCalibration/blob/6264bec39e22645006f33b4346872adada4a1ef4/interactive_calibration/src/interactive_calibration/interactive_data_labeler.py#L112

Will try to fix this ...

**Comment by miguelriemoliveira** [comment]
Hi @eupedrosa ,

the problem here is that you have the timercallback inside the **interactive_data_labeller** periodically clustering the data, but when the user saves a collection the **data_collector_and_labeller** actually waits for new messages which have not been labelled. 

Perhaps it is not noticeable for high streaming frequencies, but we should save to the json the sensor data message with the corresponding labels for that particular message, not for a previous one.

Is it clear now?

**Comment by eupedrosa** [comment]
Now I understand.
This explains something that happened to me. I clicked to collect data when the chessboard was properly detected but the one that was actually save failed to detect. I was using a replay with a rate of 0.5.

**Comment by miguelriemoliveira** [comment]
Solved. @eupedrosa if you see again what you described let me know ... it should not happen ...
