### ISSUE TITLE
Compressed Depth image and republish

### ISSUE THREAD

**Issue by afonsocastro** [lardemua/AtlasCarCalibration#75]

**Comment by miguelriemoliveira** [comment]
From what I read here this should work. I will try once I have time and a camera nearby.

https://wiki.ros.org/compressed_depth_image_transport

**Comment by eupedrosa** [comment]
You should also take a look at this https://wiki.ros.org/dynamic_reconfigure
Specially the `dynparam` command-line tool. It can be uses to change the parameters.

**Comment by miguelriemoliveira** [comment]
Thanks, but this is the same functionality as when we did:

`rosparam set/get <param_name> <param_value>`

https://wiki.ros.org/rosparam

Or am I missing something?

**Comment by miguelriemoliveira** [comment]
@afonsocastro since you are at the atlascar can I also ask you to check the frequency of the topic

/top_center_rgbd_camera/depth/image/compressedDepth (or something similar)

using a 

rostopic hz <topic name>

**Comment by afonsocastro** [comment]
frequency = 3.6 hz ?

![Screenshot from 2019-12-04 00-07-05](https://user-images.githubusercontent.com/47828797/70100592-167dc480-162a-11ea-828c-9acbc7244633.png)

**Comment by miguelriemoliveira** [comment]
Yes, this is the problem we had yesterday, the frequency is too slow ...

**Comment by eupedrosa** [comment]
>Thanks, but this is the same functionality as when we did:
>
>rosparam set/get <param_name> <param_value>
>
>https://wiki.ros.org/rosparam
>
>Or am I missing something?

You are missing something, `dynparam` is used to tell the a node to load the parameters from the param server.

https://wiki.ros.org/dynamic_reconfigure

**Comment by miguelriemoliveira** [comment]
Closed by https://github.com/lardemua/atlas-core/commit/417ca9e5aef489ca12851b61d3bf7f607b3c3772
