### ISSUE TITLE
Change the name of the frontal_rgbd_camera to top_frontal_rgbd_camera

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/AtlasCarCalibration#76]
Hi @afonsocastro ,

a refactor should help to do this. I can help.

**Comment by miguelriemoliveira** [comment]
I am on it ...

**Comment by miguelriemoliveira** [comment]
Done, changed to "top_center_rgbd_camera" to be more consistent with "top_left_camera". Cannot verify if it is working, @afonsocastro , can you test tomorrow?

If it works please close the issue ...

**Comment by afonsocastro** [comment]
I will test it now, im working on atlascar

**Comment by miguelriemoliveira** [comment]
Thanks!

**Comment by afonsocastro** [comment]
It all works! but rviz gives a warning:

![Screenshot from 2019-12-03 23-18-43](https://user-images.githubusercontent.com/47828797/70098257-58efd300-1623-11ea-84c6-c875dc24317e.png)

**Comment by miguelriemoliveira** [comment]
I think that was there before this afternoon (@eupedrosa can you conform?), so I would say the refactor worked.

Waiting for @eupedrosa to close. 

Thanks @afonsocastro !

**Comment by eupedrosa** [comment]
It is a strange warning. I think the warning we saw was different. Maybe it is worth trying to understand what is happening.
