### ISSUE TITLE
Sensors first guess's orientation isn't correctly saved

### ISSUE THREAD

**Issue by afonsocastro** [lardemua/AtlasCarCalibration#8]
`     for joint in robot.joints:
            for sensor in robot.sensors:
                if sensor.parent == joint.child:
                    optimization_parent_link = joint.parent
            for mp in marker_poses:
                (trans, rot) = listener2.lookupTransform(optimization_parent_link, mp.child_frame_id,rospy.Time(0))
                if joint.child + "_first_guess" == mp.child_frame_id:
                    joint.origin.xyz[0] = trans[0]
                    joint.origin.xyz[1] = trans[1]
                    joint.origin.xyz[2] = trans[2]
                    joint.origin.rpy[0] = rot[0]
                    joint.origin.rpy[1] = rot[1]
                    joint.origin.rpy[2] = rot[2] `

**Comment by miguelriemoliveira** [comment]
Hi @afonsocastro ,

try it out with my code, I think it is working ...

```bash
rosrun interactive_marker_test create_first_guess.py -w car_center
```

**Comment by miguelriemoliveira** [comment]
And don't forget to assign someone to this issue as well ...

**Comment by afonsocastro** [comment]
yap, it's working well with your code
