### ISSUE TITLE
Do you like my Pose?

### ISSUE THREAD

**Issue by eupedrosa** [lardemua/AtlasCarCalibration#82]
Hi,
Good News Everybody !!
I got an initial version of the optimization running (and working!!!). Here is a short clip with the poses provided by the optimization.
![first_optimization](https://user-images.githubusercontent.com/6196901/70378141-ffceba80-1914-11ea-9d45-003b4888552c.gif)

**Comment by eupedrosa** [comment]
For reference, this was the *first guess*
![reference_pose](https://user-images.githubusercontent.com/6196901/70378270-3f49d680-1916-11ea-9e2e-a6e249198037.gif)

**Comment by miguelriemoliveira** [comment]
This is really nice. In the first video, the overlap of the virtual robot arm with the video from the calibrated camera looks fantastic. Congratullations!

One more paper to write :-)?

**Comment by miguelriemoliveira** [comment]
For writting a paper it would be nice to get a calibration usin standard tools (visp eye in world). You said your students succsessfully did this?

also, the comparison should be numeric, so you should compute the reprojection error for all collections and plot it. 

@afonsocastro did this before, perhaps he can tell you how to do it  really quick ...

**Comment by miguelriemoliveira** [comment]
@tiagomfmadeira you should see this as well ...

**Comment by miguelriemoliveira** [comment]
white background everywhere for the papers please :-)

**Comment by eupedrosa** [comment]
> This is really nice. In the first video, the overlap of the virtual robot arm with the video from the calibrated camera looks fantastic. 

I was surprised that it work so well. I used 25 collections and it took 16 seconds to optimize.
But there are a few details we have to discuss before moving forward. Next Tuesday would be nice.

> For writting a paper it would be nice to get a calibration usin standard tools (visp eye in world). You said your students succsessfully did this?

I have to re-check this next week. Last time I asked them they said *yes*, but I need more details.

**Comment by afonsocastro** [comment]
This looks very nice!! The poses really improved from the first guess. Yes, I can help with the visualization of the reprojection errors.

**Comment by eupedrosa** [comment]
More news Everbody!!!
This is the eye-in-hand problem, solved by our framework.
![eye_in_hand](https://user-images.githubusercontent.com/6196901/70717279-edbe9480-1ce5-11ea-8d50-85dff29a6eec.gif)

I tried to change the background to white but without success :cry:

**Comment by miguelriemoliveira** [comment]
Congratullations , looks great! One question: the reference frame we see in the image is **detected**, right? If so, it is not a measure of how good the calibration is the good fit of the reference frame w.r.t the chess. Thus I would hide it. We just look at the perfect overlap between real robot and robot image.

You are doing it with charucos, great!

Can't find a way to set the background to white as well ... : - (


I am starting to feel jealous, you get all the nice results and we can't find a way to get the 2D Lidars working : - )

**Comment by miguelriemoliveira** [comment]
:1st_place_medal:

**Comment by eupedrosa** [comment]
The reference frame that you see in the image is **not detected**. It is the pose of the pattern provided by the optimization.

> I am starting to feel jealous, you get all the nice results and we can't find a way to get the 2D Lidars working : - )

I got the easy part!!!

**Comment by miguelriemoliveira** [comment]
> The reference frame that you see in the image is not detected. It is the pose of the pattern provided by the optimization.

Even better then. There are really nice results.

**Comment by miguelriemoliveira** [comment]
Can we close this @eupedrosa ? This is the issue that leaves me very jealous : -)

**Comment by eupedrosa** [comment]
Yes. I think that we can close this issue.
