### ISSUE TITLE
Acquiring Callibration Targets

### ISSUE THREAD

**Issue by eupedrosa** [lardemua/AtlasCarCalibration#83]
https://calib.io/

**Comment by miguelriemoliveira** [comment]
Hi @afonsocastro , @tiagomfmadeira  and @eupedrosa , don't forget to add the issues to our project, otherwise I miss them ...

**Comment by miguelriemoliveira** [comment]
Hi,

was looking at this. I think we should get a couple of calibration patterns. Not sure how the 2d lidar behaves, but in any case ...

I vote for this 

https://calib.io/products/charuco-targets?variant=9400455004207

it is a charuco with 800x600 mm

**Comment by miguelriemoliveira** [comment]
I can talk to Vitor to see if we have funding ...

**Comment by miguelriemoliveira** [comment]
Hi @aaguiar96 read this
