### ISSUE TITLE
Pass calibration_config json file ccontent to data_collected.json

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/AtlasCarCalibration#84]
Some calibration configurations are required for the optimization.

**Comment by miguelriemoliveira** [comment]
First we must ensure calibConfig funcion creates a dictionary

**Comment by miguelriemoliveira** [comment]
Hi @eupedrosa , you will fix this? Leave it open?

**Comment by eupedrosa** [comment]
I will fix this.
