### ISSUE TITLE
List problems in the 5th of  December bag file

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/AtlasCarCalibration#85]
Please add everything you notice ...

A lot of time with chessboard not seen from cameras ... 

![image](https://user-images.githubusercontent.com/11350998/70536117-16178900-1b56-11ea-97ef-6e4611612d7f.png)

**Comment by tiagomfmadeira** [comment]
Keep the chessboard away from the holder's body to ease segmentation.

**Comment by miguelriemoliveira** [comment]
my bad, my bag ...
