### ISSUE TITLE
Consider the detection of a charuco board

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/AtlasCarCalibration#87]

**Comment by eupedrosa** [comment]
I got the charuco detection working.

![charuco](https://user-images.githubusercontent.com/6196901/70617186-f3de4380-1c07-11ea-898f-eb3abfd257a7.gif)

The detection time is around 10ms, even if there is no board or only a partial part is detected.
Here is an image of a partial detection.
![charuco_partial](https://user-images.githubusercontent.com/6196901/70617350-4ddf0900-1c08-11ea-99b9-d855e7b2540f.png)

Just to say that I already have a dataset for the eye-in-hand problem. I will try to work on this today.
I have no idea where the camera is...
![IMG_20191211_112353](https://user-images.githubusercontent.com/6196901/70617637-ee352d80-1c08-11ea-925b-f5a83d43fa54.jpg)

**Comment by miguelriemoliveira** [comment]
Hi @eupedrosa 
Looks good. What about the failures, i.e. when there is no charuco board for example, how does it behave?

**Comment by eupedrosa** [comment]
> What about the failures, i.e. when there is no charuco board for example, how does it behave?

Behaves very well!!!! It is faster when there is *no* board. It is the opposite from the class chessboard detector.

**Comment by miguelriemoliveira** [comment]
Sounds good, but to change all the code to arucos right now would be a gigantic task ... are you moving forward with the aruco hand in eye calibration? We, on our side, can just read the json and for now, if the marker is an aruco, abort sayin "unsuported marker type" ...

**Comment by miguelriemoliveira** [comment]
but what about the data collector and labeller ...

**Comment by eupedrosa** [comment]
> Sounds good, but to change all the code to arucos right now would be a gigantic task ... 

Maybe not. The charuco board also provides the corners of pattern. The information is the same but extracted with a different method. My idea is to support both patterns and atlas car dataset will work without a problem.

> are you moving forward with the aruco hand in eye calibration?

Yes I am. Using charuco boards is a breeze.
Stay tuned...
