### ISSUE TITLE
New distance to chessboard for lasers cost function

### ISSUE THREAD

**Issue by afonsocastro** [lardemua/AtlasCarCalibration#93]
The computed distance from each point to the chessboard should not be orthogonal to the chess plan.
Instead, it should be the distance measured in the laser beam direction.

**Comment by afonsocastro** [comment]
Working! doesn't have a visualization function, but I am pretty sure that it is all correct! :D
For the skeptic ones, we could always develop this visual tool later....

**Comment by miguelriemoliveira** [comment]
This is not working, reopening 

![image](https://user-images.githubusercontent.com/11350998/71307411-e5511280-23e5-11ea-8a1b-9c32b9dac243.png)

**Comment by miguelriemoliveira** [comment]
Hi @afonsocastro ,

when will you have time to work on this? If you do not have time I will try to implement it myself ...

**Comment by miguelriemoliveira** [comment]
Drawing is always better ... I am never sure if the code is working before drawing ... (**actually I am sure it is not working**)

![image](https://user-images.githubusercontent.com/11350998/71368338-96e77380-259f-11ea-9e14-5ccbdf79774d.png)

**Comment by miguelriemoliveira** [comment]
![image](https://user-images.githubusercontent.com/11350998/71369126-b8495f00-25a1-11ea-875b-86dcc096417c.png)

![image](https://user-images.githubusercontent.com/11350998/71369202-ed55b180-25a1-11ea-84ef-f4c8e12d7090.png)

![image](https://user-images.githubusercontent.com/11350998/71369221-f9da0a00-25a1-11ea-8ec2-327261e440de.png)

New function is working as intended. Here's some pictures.

**Comment by miguelriemoliveira** [comment]
One more picture just to piss off @afonsocastro : - )

![image](https://user-images.githubusercontent.com/11350998/71370926-60adf200-25a7-11ea-9875-036ff0ff2f59.png)

**Comment by miguelriemoliveira** [comment]
and another using two lasers ...

![image](https://user-images.githubusercontent.com/11350998/71371271-7ff94f00-25a8-11ea-8cc6-e228bacf0576.png)

**Comment by miguelriemoliveira** [comment]
The results are similar to the ones before ...

![image](https://user-images.githubusercontent.com/11350998/71371373-d23a7000-25a8-11ea-94ff-98b6469a29ac.png)

**Comment by eupedrosa** [comment]
@miguelriemoliveira do you have the intrinsic optimization on?

**Comment by miguelriemoliveira** [comment]
Yes.

https://github.com/miguelriemoliveira/OptimizationUtils/blob/5e9d06de886662c83106465b42ab09f1e38bfe7f/test/sensor_pose_json_v2/main.py#L222-L226

**Comment by afonsocastro** [comment]
Yap, visual feedback is essential! And now it's working just fine, thanks :)
